### ISSUE TITLE
Update to qooxdoo 4.1

### ISSUE THREAD

**Issue by jbaron** [jbaron/cats#140]
Since qooxdoo 4.1 is out, time to upgrade.

- First step is to get the qooxdoo.d.ts regenerated (part of another project). 
- Then to see what has changed and isn't downwards compatible (this should not be too much effort)

**Comment by tcsaddul** [comment]
I'm looking forward to this update in qx-typed though I don't see any issue with the current version.  Thank you for making qooxdoo available in the TypeScript language.
