### ISSUE TITLE
Save command fails in latest stable (1.4.0)

### ISSUE THREAD

**Issue by mindplay-dk** [jbaron/cats#145]
To repeat:

1. Create an empty folder
2. Open folder as Project
3. Create a new file
4. Input some code
5. Press CTRL+S

At this point an exception occurs:

```
4:55:40 PM TypeError: Arguments to path.resolve must be strings
4:55:40 PM at Object.win32.resolve (path.js:89:13)
4:55:40 PM at Object.writeTextFile (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/lib/main.js:590:38)
4:55:40 PM at EditSession.save (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/lib/main.js:3933:34)
4:55:40 PM at SourceEditor.save (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/lib/main.js:3282:38)
4:55:40 PM at Object.editor.commands.addCommands.exec (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/lib/main.js:3269:39)
4:55:40 PM at file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/resource/ace/ace.js:1:178963
4:55:40 PM at r._emit.r._dispatchEvent (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/resource/ace/ace.js:1:48589)
4:55:40 PM at exec (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/resource/ace/ace.js:1:179202)
4:55:40 PM at $callKeyboardHandlers (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/resource/ace/ace.js:1:59715)
4:55:40 PM at onCommandKey (file:///C:/Users/RASMUS~1/AppData/Local/Temp/nw5808_28876/resource/ace/ace.js:1:59908)
```

6. Enter a filename and press OK

At this point, nothing happens - the file doesn't get saved.

Workaround: go to the menu and select "Save as", everything works as expected.

Suggested fix: the "Save" command probably just needs to check if the file is new, and if so, trigger the "Save as" command instead.

**Comment by jbaron** [comment]
Thanks for finding and reporting  this (perhaps not that stable after all :)

Was a mistake in the save EditorSession code (since we changed the popups asking for a filename to be async, the save code was executed too soon). Fixed just now in the latest master.

**Comment by mindplay-dk** [comment]
Off-topic (sorry) but, have you tried [atom-typescript](https://github.com/TypeStrong/atom-typescript) under [ATOM](https://atom.io/)?

ATOM is also based on Javascript and WebKit, so put together, this solution is actually quite similar to CATS, but with a very extensible architecture and already very good community support - lots of plugins, nice developer tools, etc.

I wonder if you would consider joining forces? This project could use your expertise, and likely some features (like your structure panel) could be ported/integrated to ATOM. CATS is great, but it's largely a one-man effort, and the ATOM editor already has a lot of peripheral editor features that would take a long time for one man to duplicate.

The work you've done so far is fantastic, I just think your efforts could have more impact in concert with all the other peripheral features that are rapidly being added to ATOM by a growing community.

Just a thought :-)

**Comment by jbaron** [comment]
For me the main reason to write CATS is to play around with TypeScript a bit. I want to see if with the use of TypeScript, traditional type of development environments could be achieved. How close can one get to the Eclipse and VisualStudio type of development experience. (BTW if you look at the overall structure, you can see I used a lot of clues from Eclipse).

Atom itself doesn’t use TS as far as I know (coffee-script right ?), so using/modifying that as a foundation doesn't really contribute to my above "learning goals".

However it does perhaps make sense to align the api/external-module structure to an popular editor like Atom or Cloud9. That way people could use other modules more easily within CATS if they want to. So should put that one on the list.  


— Peter

**Comment by mindplay-dk** [comment]
> However it does perhaps make sense to align the api/external-module structure to an popular editor like Atom or Cloud9

Is that possible? That would be the best of both worlds :-)
