### ISSUE TITLE
Purpose of custom run environment value?

### ISSUE THREAD

**Issue by adamcarr** [jbaron/cats#146]
I assumed this would set environment variables with available to the process that is set to run. I used the ENV_VAR_NAME=mycustomvalue syntax but this isn't working. I don't see any documentation on this. Am I not using this right?

**Comment by jbaron** [comment]
Missed this question before, sorry for that. 

Could you elaborate on what you try to achieve? All the CATS options are right now command line options only. So these options cannot ebe set as environment variables if that is what you are looking for,
