### ISSUE TITLE
Open last project

### ISSUE THREAD

**Issue by dtrillo** [jbaron/cats#147]
I would like a new feature: to open the last project, instead of searching for the path, because normally you work on a project for some days. I guess the path can be saved on the config file every time CATS is closed.

**Comment by jbaron** [comment]
Actually there is already some support:

1) You can open any recent project from the main menu: Project -> “Recent Projects” -> <pick your path>
    I use this myself all the time 

2) You start CATS with the —restore option that will restore your last open project (and its open editors). Don’t use this myself too much, so might still be some glitches.

3)  You start CATS with the —project <your path> option. I also use this a lot. You can create a shortcut so you don’t have to type it all the time of course.

**Comment by dtrillo** [comment]
Thank you for the options!
I'm surprised for the CATS IDE. Congrats!
