### ISSUE TITLE
Tile files

### ISSUE THREAD

**Issue by dtrillo** [jbaron/cats#149]
i wonder if you could add to the editor the possibility of having two open files under the same view. It's a feature used very common in Sublime Text and other editor, and I don't know if maybe this feature can be implemented also in CATS.

I'm very happy using CATS, mainly because I have a portable IDE.

**Comment by jbaron** [comment]
Not fully aware of the sublime editor features. What does it mean to have two open files under the same view? Is it kind of seeing two editors side by side (so you can easily compare the two of them) or do you mean having the same file open twice in different editor tabs ?

P.S Good to hear you using CATS. Right now in the process of updating to the latest language services.

**Comment by dtrillo** [comment]
Yes, it's a cool IDE. I would like to have more "preferences", such as Open last project automatically, or setting properties for a project as defaults.

Keep in inform of new changes for testing, if you want.

The main reason I have for having two files opened on a single view is for avoiding errors. For example, you can have the interface with properties on one file, and in other, the HTML view that you're building for this object.
In large projects, it could be great if you can have this feature, but of course, you can survive with tabs!

I'm only proposing! Another issue if it can't be implemented!

**Comment by jbaron** [comment]
Ok, understand. So the problem is right now you cannot see them at the same time. 

Perhaps a nice option would be able to detach an editor tab into a seperate window (and attach it back later again). Will put this on the todo list.

**Comment by jbaron** [comment]
Created a todo item
