### ISSUE TITLE
Qooxdoo.js file unminified release

### ISSUE THREAD

**Issue by tcsaddul** [jbaron/cats#151]
Is it possible to release qooxdoo.js unminified?  I have a need to edit Appearance.js and Decoration.js but is not possible for the minified qooxdoo.js

**Comment by jbaron** [comment]
For creating the qooxdoo,js file I use a standard project with some custom main file and generate.py does the rest. 
I looked in the config and commandline options of generate.py but couldn’t find an option to skip the minify stage. Will look a bit more later.

However in case you know it, just let me know and I’m happy to run the build with that option enabled.

**Comment by dtrillo** [comment]
Last week, http://news.qooxdoo.org/qooxdoo-5-0-released a new version is ready to use!

I am wondering when can we try a new version of CATS?

**Comment by jbaron** [comment]
Thanks for the info (missed that announcement). With TypeScript 1.5 beta out and now qooxdoo 5.0 it seems indeed time to update CATS.

**Comment by dtrillo** [comment]
I'm looking foward to it! Please, let me know when I can test the new version of CATS. I'm using it every day, and indeed, templates should be a prioritary feature for version 2 of CATS.

**Comment by jbaron** [comment]
Just updated master branch of CATS both to Qooxdoo 5.0 and latest version of TS. 

Will still need to do some more testing and after that will create a new official release. So for now only as source code available in the master branch.

**Comment by dtrillo** [comment]
OK. I'll try to give it a try using the source code!

**Comment by tcsaddul** [comment]
Thank you for this update. Will try it out too.
 


     On Monday, June 29, 2015 6:24 AM, David Trillo <notifications@github.com> wrote:
   

 OK. I'll try to give it a try using the source code!—

**Comment by tcsaddul** [comment]
After updating to the latest, here are my findings:
1.  qooxdoo.js -- no errors
2.  qooxdoo.d.ts  --> no errors
3.  lib.es6.d.ts  --> many errors,  used the older version ---> no errors
4.  resource folder -->  used resource from github's qooxdoo ---> no errors

**Comment by jbaron** [comment]
I have to check about lib.es6.d.ts (I use myself so far mostly lib.d.ts).

**Comment by dtrillo** [comment]
Version 1.5 of TypeScript was launch! Do we have something to do in order to compile to it using CATS? Or, another way around: can we build our TS files to TS 1.5?

**Comment by jbaron** [comment]
I updated CATS to now use 1.5.3 (TS 1.5). Both the master is using this but also the release is now using this.

**Comment by tcsaddul** [comment]
Thanks a lot. Have updated mine and it works flawlessly.

**Comment by dtrillo** [comment]
Is the CATS binary package updated, or do I have to use the source code?

**Comment by jbaron** [comment]
It is now :)

Actually the build of the binary is fully automated (jake dist), although it works only on OSX and Linux due to using some shell commands. However never found a way to automatically  upload it to github as part of the release.
