### ISSUE TITLE
Alt+F twice doesn't clear find text box

### ISSUE THREAD

**Issue by paf31** [jbaron/cats#154]
First of all, thanks so much for working on this IDE. It's really great.

I would really like it if, when I have the Find/Replace dialog already open and press Alt+F again, the current text is selected, so that I can find something new without having to press backspace to erase it.

**Comment by jbaron** [comment]
Actually this is how it works on my OSX machine (although there it is <CMD> - F) and thought this would also apply to other OS (since only the keybinding is different). 

What OS and version of CATS are you using?
