### ISSUE TITLE
No compilation with version 1.6.360

### ISSUE THREAD

**Issue by dtrillo** [jbaron/cats#155]
I am testing version 1.6.360, and it doesn't compile anything. If I try with 1.5.348, everything is perfect!

**Comment by jbaron** [comment]
Actually found out I made a trivial mistake. I just uploaded the fix to master branch but can only later generate a new binary release.

P.S Tip of the day: Don't declare the same variable name within a loop as outside :)

**Comment by jbaron** [comment]
Version 1.6.362 should work again.
