### ISSUE TITLE
TSX support

### ISSUE THREAD

**Issue by xmehaut** [jbaron/cats#157]
Hello,

cats is a very nice typescipt iDE. Unfortunately I deelop with react and I need to use TSX ... Is it planned to add this in CATS?

regards

**Comment by jbaron** [comment]
Had a quick look and should not be too hard to add support since CATS
already uses the TS version that supports JSX.

Still to be done:

1) When scanning for files also scan for .tsx extensions.
2) Add the option to enable TSX (in the compiler options sections)

**Comment by xmehaut** [comment]
thanks :)

do you already take into account tsconfig.json otherwise? and if so, with
automatic filling each time a new file is added , removed or moved?

2015-11-03 14:07 GMT+01:00 Peter <notifications@github.com>:

> Had a quick look and should not be too hard to add support since CATS
> already uses the TS version that supports JSX.
>
> Still to be done:
>
> 1) When scanning for files also scan for .tsx extensions.
> 2) Add the option to enable TSX (in the compiler options sections)
>
>
>

**Comment by jbaron** [comment]
Right now CATS uses its own config file. It pre-dates the tsconfig file but
is very simular in structure and layout. It alos has a GUI to configure it.
I would like to move the tsconfig file but a lot is missing that is
requried for CATS. So either I have to extend it or have two config files.

**Comment by xmehaut** [comment]
yes , two files would be right, the CATS's one being specific to CATS

2015-11-03 15:06 GMT+01:00 Peter <notifications@github.com>:

> Right now CATS uses its own config file. It pre-dates the tsconfig file but
> is very simular in structure and layout. It alos has a GUI to configure it.
> I would like to move the tsconfig file but a lot is missing that is
> requried for CATS. So either I have to extend it or have two config files.
>

**Comment by dtrillo** [comment]
I don't see any problem in having two config files!

**Comment by jbaron** [comment]
Added some support for TSX. Now it should recognise files with TSX extension as "TypeScript" files. Unfortunately the editor (ACE) doesn't have a mode yet for it. So the default text editor will be started.

**Comment by jbaron** [comment]
Now also: 

- Updated Ace and fixed so it recognises tax file and applies the TS mode.
- You can set the compilation target for TSX from within CATS (in case you don't use external build tools)

So full TSX support in place,

**Comment by xmehaut** [comment]
Thanks !

2016-01-18 13:51 GMT+01:00 Peter <notifications@github.com>:
